# Generated by Django 4.2.7 on 2026-04-18 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUploadQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_files_per_day", models.PositiveIntegerField(default=50)),
                ("max_storage_mb", models.PositiveIntegerField(default=1000)),
                ("max_file_size_mb", models.PositiveIntegerField(default=100)),
                ("files_today", models.PositiveIntegerField(default=0)),
                ("storage_used_mb", models.PositiveIntegerField(default=0)),
                ("last_reset_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_upload_quota",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_url", models.URLField(blank=True)),
                ("thumbnail_path", models.CharField(blank=True, max_length=500)),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_progress", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("compress_applied", models.BooleanField(default=False)),
                ("filters_applied", models.JSONField(blank=True, default=list)),
                ("is_scanned", models.BooleanField(default=False)),
                ("scan_result", models.CharField(blank=True, max_length=20)),
                ("is_approved", models.BooleanField(default=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "uploaded_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileProcessingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("thumbnail", "Thumbnail Generation"),
                            ("compression", "Compression"),
                            ("filter", "Filter Application"),
                            ("analysis", "Content Analysis"),
                            ("moderation", "Content Moderation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_tasks",
                        to="upload.uploadedfile",
                    ),
                ),
            ],
            options={
                "db_table": "file_processing_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentModerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("auto_approve", "Auto Approve"),
                            ("manual_approve", "Manual Approve"),
                            ("reject", "Reject"),
                            ("flag", "Flag for Review"),
                            ("delete", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("details", models.TextField(blank=True)),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("ai_flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="upload.uploadedfile",
                    ),
                ),
            ],
            options={
                "db_table": "content_moderation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("file_size", models.BigIntegerField()),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="initialized",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("file_key", models.CharField(blank=True, max_length=500)),
                ("upload_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upload_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="upload_sess_user_id_73c91f_idx"
                    ),
                    models.Index(
                        fields=["file_id"], name="upload_sess_file_id_9f3c81_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="upload_sess_created_3de5bb_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["user", "upload_status"], name="uploaded_fi_user_id_b40f24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["file_id"], name="uploaded_fi_file_id_5c81fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["file_type"], name="uploaded_fi_file_ty_206d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["created_at"], name="uploaded_fi_created_f8998f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["upload_status"], name="uploaded_fi_upload__d52de3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileprocessingtask",
            index=models.Index(
                fields=["uploaded_file", "task_type"],
                name="file_proces_uploade_474bf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileprocessingtask",
            index=models.Index(fields=["status"], name="file_proces_status_601689_idx"),
        ),
        migrations.AddIndex(
            model_name="fileprocessingtask",
            index=models.Index(
                fields=["celery_task_id"], name="file_proces_celery__0da2ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentmoderationlog",
            index=models.Index(
                fields=["uploaded_file", "action"],
                name="content_mod_uploade_772021_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentmoderationlog",
            index=models.Index(
                fields=["moderator"], name="content_mod_moderat_befbda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentmoderationlog",
            index=models.Index(
                fields=["created_at"], name="content_mod_created_cc952c_idx"
            ),
        ),
    ]
