# Generated by Django 4.2.7 on 2026-04-18 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=2200)),
                ("video_file", models.FileField(upload_to="reels/videos/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="reels/thumbnails/"
                    ),
                ),
                ("duration", models.FloatField(help_text="Duration in seconds")),
                ("width", models.IntegerField(default=720)),
                ("height", models.IntegerField(default=1280)),
                ("is_private", models.BooleanField(default=False)),
                ("allow_comments", models.BooleanField(default=True)),
                ("allow_duet", models.BooleanField(default=True)),
                ("allow_share", models.BooleanField(default=True)),
                ("music_track", models.CharField(blank=True, max_length=200)),
                ("hashtags", models.JSONField(default=list)),
                ("mentions", models.JSONField(default=list)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReelChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("hashtag", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("prize", models.CharField(blank=True, max_length=200)),
                ("rules", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReelHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_trending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="ReelMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("audio_file", models.FileField(upload_to="reels/music/")),
                ("duration", models.FloatField()),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_trending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-usage_count"],
                "unique_together": {("title", "artist")},
            },
        ),
        migrations.CreateModel(
            name="ReelRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("reason", models.CharField(max_length=200)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="reels.reel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "-score", "-created_at"],
                        name="reels_reelr_user_id_761469_idx",
                    ),
                    models.Index(
                        fields=["reel", "-score"], name="reels_reelr_reel_id_f7bc41_idx"
                    ),
                ],
                "unique_together": {("user", "reel")},
            },
        ),
        migrations.CreateModel(
            name="ReelInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("save", "Save"),
                            ("duet", "Duet"),
                            ("view", "View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="reels.reel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["reel", "interaction_type", "-created_at"],
                        name="reels_reeli_reel_id_b67cad_idx",
                    ),
                    models.Index(
                        fields=["user", "interaction_type", "-created_at"],
                        name="reels_reeli_user_id_987ef0_idx",
                    ),
                ],
                "unique_together": {("reel", "user", "interaction_type")},
            },
        ),
        migrations.CreateModel(
            name="ReelForward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from sender",
                        max_length=500,
                    ),
                ),
                (
                    "is_saved",
                    models.BooleanField(
                        default=False, help_text="Whether recipient has saved the reel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reel_forwards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forwards",
                        to="reels.reel",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_reel_forwards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="reels_reelf_recipie_865ca5_idx",
                    ),
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="reels_reelf_sender__ba2526_idx",
                    ),
                    models.Index(
                        fields=["reel", "-created_at"],
                        name="reels_reelf_reel_id_a5584f_idx",
                    ),
                    models.Index(
                        fields=["is_saved", "-created_at"],
                        name="reels_reelf_is_save_314c2b_idx",
                    ),
                ],
                "unique_together": {("reel", "sender", "recipient")},
            },
        ),
        migrations.CreateModel(
            name="ReelComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("is_deleted", models.BooleanField(default=False)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reels.reelcomment",
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reels.reel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["reel", "-created_at"],
                        name="reels_reelc_reel_id_838a07_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="reels_reelc_user_id_ebe2ca_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReelChallengeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("votes", models.PositiveIntegerField(default=0)),
                ("is_winner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="reels.reelchallenge",
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reels.reel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-votes"],
                "unique_together": {("challenge", "reel")},
            },
        ),
        migrations.CreateModel(
            name="ReelAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reels_created", models.PositiveIntegerField(default=0)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("total_likes", models.PositiveIntegerField(default=0)),
                ("total_comments", models.PositiveIntegerField(default=0)),
                ("total_shares", models.PositiveIntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["creator", "-created_at"], name="reels_reel_creator_e75a2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["is_trending", "-view_count"],
                name="reels_reel_is_tren_5f99b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(
                fields=["is_featured", "-created_at"],
                name="reels_reel_is_feat_1fc81e_idx",
            ),
        ),
    ]
