# Generated by Django 4.2.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('content_type', models.CharField(choices=[('reel', 'Reel'), ('post', 'Post')], max_length=20)),
                ('content_id', models.UUIDField(db_index=True)),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2000)])),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'indexes': [
                    models.Index(fields=['content_type', 'content_id', 'created_at'], name='comments_comment_content_2b5c5f_idx'),
                    models.Index(fields=['user', 'created_at'], name='comments_comment_user_id_8f1c3a_idx'),
                    models.Index(fields=['parent', 'created_at'], name='comments_comment_parent_4d7e8c_idx'),
                    models.Index(fields=['created_at'], name='comments_comment_create_a4b7d2_idx'),
                ],
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_likes',
                'indexes': [
                    models.Index(fields=['comment', 'created_at'], name='comments_commentlik_comment_8f1c3a_idx'),
                    models.Index(fields=['user', 'created_at'], name='comments_commentlik_user_id_2b5c5f_idx'),
                ],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='comments.comment')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_mentions',
                'indexes': [
                    models.Index(fields=['mentioned_user', 'is_read', 'created_at'], name='comments_commentment_mention_8f1c3a_idx'),
                    models.Index(fields=['comment', 'created_at'], name='comments_commentment_comment_2b5c5f_idx'),
                ],
                'unique_together': {('comment', 'mentioned_user')},
            },
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('content_type', models.CharField(choices=[('reel', 'Reel'), ('post', 'Post')], max_length=20)),
                ('content_id', models.UUIDField(db_index=True)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('last_comment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_threads',
                'indexes': [
                    models.Index(fields=['content_type', 'content_id'], name='comments_commentthrea_content_8f1c3a_idx'),
                    models.Index(fields=['last_comment_at'], name='comments_commentthrea_last_com_2b5c5f_idx'),
                    models.Index(fields=['updated_at'], name='comments_commentthrea_update_a4b7d2_idx'),
                ],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('notification_type', models.CharField(choices=[('reply', 'Reply to Comment'), ('mention', 'Mention in Comment'), ('like', 'Like on Comment'), ('thread_update', 'Thread Update')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comments.comment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_notifications',
                'indexes': [
                    models.Index(fields=['recipient', 'is_read', 'created_at'], name='comments_commentnoti_recipien_8f1c3a_idx'),
                    models.Index(fields=['comment', 'created_at'], name='comments_commentnoti_comment_2b5c5f_idx'),
                    models.Index(fields=['notification_type', 'created_at'], name='comments_commentnoti_notific_4d7e8c_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('inappropriate', 'Inappropriate Content'), ('off_topic', 'Off-topic'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('action_taken', models.CharField(choices=[('none', 'None'), ('deleted', 'Deleted'), ('user_warned', 'User Warned'), ('user_suspended', 'User Suspended')], default='none', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment_reports',
                'indexes': [
                    models.Index(fields=['comment', 'created_at'], name='comments_commentrepo_comment_8f1c3a_idx'),
                    models.Index(fields=['reporter', 'created_at'], name='comments_commentrepo_reporte_2b5c5f_idx'),
                    models.Index(fields=['is_reviewed', 'created_at'], name='comments_commentrepo_is_review_4d7e8c_idx),
                ],
                'unique_together': {('comment', 'reporter')},
            },
        ),
    ]
