# Generated by Django 4.2.7 on 2026-04-18 03:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("reel", "Reel"), ("post", "Post")], max_length=20
                    ),
                ),
                ("content_id", models.UUIDField(db_index=True)),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(2000),
                        ]
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("replies_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("reel", "Reel"), ("post", "Post")], max_length=20
                    ),
                ),
                ("content_id", models.UUIDField(db_index=True)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("participants_count", models.PositiveIntegerField(default=0)),
                ("last_comment_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_comment_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_threads",
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="comment_thr_content_ba27c9_idx",
                    ),
                    models.Index(
                        fields=["last_comment_at"],
                        name="comment_thr_last_co_dcaafc_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="comment_thr_updated_d4871b_idx"
                    ),
                ],
                "unique_together": {("content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("hate_speech", "Hate Speech"),
                            ("inappropriate", "Inappropriate Content"),
                            ("off_topic", "Off-topic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("deleted", "Deleted"),
                            ("user_warned", "User Warned"),
                            ("user_suspended", "User Suspended"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="comments.comment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_reports",
                "indexes": [
                    models.Index(
                        fields=["comment", "created_at"],
                        name="comment_rep_comment_2bcfb2_idx",
                    ),
                    models.Index(
                        fields=["reporter", "created_at"],
                        name="comment_rep_reporte_b3632a_idx",
                    ),
                    models.Index(
                        fields=["is_reviewed", "created_at"],
                        name="comment_rep_is_revi_b869f1_idx",
                    ),
                ],
                "unique_together": {("comment", "reporter")},
            },
        ),
        migrations.CreateModel(
            name="CommentNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reply", "Reply to Comment"),
                            ("mention", "Mention in Comment"),
                            ("like", "Like on Comment"),
                            ("thread_update", "Thread Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="comments.comment",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_notifications",
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="comment_not_recipie_c82e03_idx",
                    ),
                    models.Index(
                        fields=["comment", "created_at"],
                        name="comment_not_comment_e8f7ab_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="comment_not_notific_447012_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="comments.comment",
                    ),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_mentions",
                "indexes": [
                    models.Index(
                        fields=["mentioned_user", "is_read", "created_at"],
                        name="comment_men_mention_823886_idx",
                    ),
                    models.Index(
                        fields=["comment", "created_at"],
                        name="comment_men_comment_bd2254_idx",
                    ),
                ],
                "unique_together": {("comment", "mentioned_user")},
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_likes",
                "indexes": [
                    models.Index(
                        fields=["comment", "created_at"],
                        name="comment_lik_comment_e1fcf0_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="comment_lik_user_id_40c748_idx",
                    ),
                ],
                "unique_together": {("comment", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "content_id", "created_at"],
                name="comments_content_de98cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "created_at"], name="comments_user_id_88f50c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent", "created_at"], name="comments_parent__149355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="comments_created_d5740c_idx"
            ),
        ),
    ]
