# Generated by Django 4.2.7 on 2026-04-18 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoFollowRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("category_match", models.JSONField(default=dict)),
                ("behavior_threshold", models.FloatField(default=0.8)),
                ("min_followers", models.IntegerField(default=0)),
                ("max_followers", models.IntegerField(blank=True, null=True)),
                ("follow_ratio_min", models.FloatField(default=0.0)),
                ("follow_ratio_max", models.FloatField(default=10.0)),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_follows_per_day", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("keywords", models.JSONField(default=list)),
                ("behavior_weights", models.JSONField(default=dict)),
                ("threshold_score", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NeuralModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.CharField(max_length=20)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("categorization", "User Categorization"),
                            ("recommendation", "Content Recommendation"),
                            ("behavior_analysis", "Behavior Analysis"),
                            ("connection_matching", "Connection Matching"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_path", models.CharField(max_length=500)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("accuracy_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNeuralProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_vector", models.JSONField(default=list)),
                ("category_scores", models.JSONField(default=dict)),
                ("behavior_patterns", models.JSONField(default=dict)),
                ("last_analyzed", models.DateTimeField(auto_now=True)),
                ("model_version", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neural_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NeuralPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("category", "Category Prediction"),
                            ("connection", "Connection Prediction"),
                            ("content", "Content Prediction"),
                            ("behavior", "Behavior Prediction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("predicted_value", models.CharField(max_length=200)),
                ("confidence_score", models.FloatField()),
                ("input_data", models.JSONField(default=dict)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neural.neuralmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neural_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("save", "Save"),
                            ("follow", "Follow"),
                            ("unfollow", "Unfollow"),
                            ("message", "Message"),
                            ("view", "View"),
                            ("skip", "Skip"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("post", "Post"),
                            ("reel", "Reel"),
                            ("story", "Story"),
                            ("profile", "Profile"),
                            ("message", "Message"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("content_id", models.CharField(blank=True, max_length=100)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neural_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="neural_user_user_id_6fc346_idx",
                    ),
                    models.Index(
                        fields=["interaction_type", "timestamp"],
                        name="neural_user_interac_22845a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AutoFollowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neural.autofollowrule",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_followed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_follow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "target_user")},
            },
        ),
    ]
