source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'pg', '~> 1.4'
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.0'
gem 'sidekiq-status', '~> 1.2'
gem 'json', '~> 2.6'
gem 'dotenv', '~> 2.8'

group :development do
  gem 'pry', '~> 0.14'
  gem 'rerun', '~> 0.14'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
end
