# Generated by Django 4.2.7 on 2026-04-18 03:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("text", "Text"),
                            ("reel_share", "Reel Share"),
                            ("post_share", "Post Share"),
                            ("profile_share", "Profile Share"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="stories/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "mov",
                                    "webm",
                                ]
                            )
                        ],
                    ),
                ),
                ("text_content", models.TextField(blank=True, null=True)),
                ("background_color", models.CharField(default="#000000", max_length=7)),
                ("text_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("caption", models.TextField(blank=True, max_length=2000)),
                (
                    "hashtags",
                    models.TextField(blank=True, help_text="Comma-separated hashtags"),
                ),
                (
                    "mentions",
                    models.TextField(blank=True, help_text="Comma-separated usernames"),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_expired", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("replies_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "view_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="View duration in seconds"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="stories.story",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_views",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["story", "viewer"],
                        name="story_views_story_i_aa7fa8_idx",
                    ),
                    models.Index(
                        fields=["viewer", "viewed_at"],
                        name="story_views_viewer__6ded1f_idx",
                    ),
                ],
                "unique_together": {("story", "viewer")},
            },
        ),
        migrations.CreateModel(
            name="StoryShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("direct_message", "Direct Message"),
                            ("post", "Post"),
                            ("external", "External"),
                            ("story", "Story"),
                        ],
                        max_length=20,
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shared_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who received the share (for DMs)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_story_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="stories.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_shares",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["story", "created_at"],
                        name="story_share_story_i_479dac_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="story_share_user_id_8365ee_idx",
                    ),
                    models.Index(
                        fields=["share_type"], name="story_share_share_t_3c0994_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_replies",
                        to="stories.storyreply",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="stories.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_replies",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["story", "created_at"],
                        name="story_repli_story_i_b1fa61_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="story_repli_user_id_1eadba_idx",
                    ),
                    models.Index(
                        fields=["parent", "created_at"],
                        name="story_repli_parent__d1eb25_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position_x",
                    models.FloatField(
                        blank=True,
                        help_text="X position of mention in story",
                        null=True,
                    ),
                ),
                (
                    "position_y",
                    models.FloatField(
                        blank=True,
                        help_text="Y position of mention in story",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_mentions",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "db_table": "story_mentions",
                "indexes": [
                    models.Index(
                        fields=["story", "mentioned_user"],
                        name="story_menti_story_i_8e7a17_idx",
                    ),
                    models.Index(
                        fields=["mentioned_user", "created_at"],
                        name="story_menti_mention_4e70b0_idx",
                    ),
                ],
                "unique_together": {("story", "mentioned_user")},
            },
        ),
        migrations.CreateModel(
            name="StoryLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_likes",
                        to="stories.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_likes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["story", "user"], name="story_likes_story_i_20e728_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="story_likes_user_id_2a3f3d_idx",
                    ),
                ],
                "unique_together": {("story", "user")},
            },
        ),
        migrations.CreateModel(
            name="StoryHighlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlight_covers",
                        to="stories.story",
                    ),
                ),
                (
                    "stories",
                    models.ManyToManyField(
                        related_name="highlights", to="stories.story"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_highlights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="story_highl_user_id_8cb6c5_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="story_highl_is_acti_d26626_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("unique_viewers", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("replies_count", models.PositiveIntegerField(default=0)),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of viewers who watched the full story",
                    ),
                ),
                (
                    "engagement_rate",
                    models.FloatField(
                        default=0.0, help_text="Engagement rate as percentage"
                    ),
                ),
                (
                    "reach",
                    models.PositiveIntegerField(
                        default=0, help_text="Unique users who saw the story"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "db_table": "story_analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["story", "date"], name="story_analy_story_i_08e47a_idx"
                    ),
                    models.Index(fields=["date"], name="story_analy_date_7730fc_idx"),
                ],
                "unique_together": {("story", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["user", "is_active", "expires_at"],
                name="stories_user_id_e65d96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["expires_at"], name="stories_expires_a4b2b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["created_at"], name="stories_created_c866ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["is_active", "is_expired"], name="stories_is_acti_a3191d_idx"
            ),
        ),
    ]
