# Generated by Django 4.2.7 on 2026-04-18 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followers_count", models.PositiveIntegerField(default=0)),
                ("following_count", models.PositiveIntegerField(default=0)),
                ("posts_count", models.PositiveIntegerField(default=0)),
                ("reels_count", models.PositiveIntegerField(default=0)),
                ("is_private", models.BooleanField(default=False)),
                ("show_activity_status", models.BooleanField(default=True)),
                ("allow_follow_requests", models.BooleanField(default=True)),
                ("total_likes_received", models.PositiveIntegerField(default=0)),
                ("total_comments_received", models.PositiveIntegerField(default=0)),
                ("total_shares_received", models.PositiveIntegerField(default=0)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("last_post_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_profil_user_id_fbe33d_idx"
                    ),
                    models.Index(
                        fields=["followers_count"],
                        name="user_profil_followe_6b6fcd_idx",
                    ),
                    models.Index(
                        fields=["following_count"],
                        name="user_profil_followi_670a4c_idx",
                    ),
                    models.Index(
                        fields=["last_activity"], name="user_profil_last_ac_ae158c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("follow", "Follow"),
                            ("post", "Post"),
                            ("reel", "Reel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=10)),
                ("content_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="user_activi_user_id_c742e0_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "created_at"],
                        name="user_activi_activit_1c12f9_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="user_activi_target__cba77e_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="user_activi_content_bc0a1a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="user_activi_created_9fa3ca_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("post", "Post"), ("reel", "Reel")], max_length=10
                    ),
                ),
                ("content_id", models.UUIDField(db_index=True)),
                ("caption", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shares",
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="shares_content_c44f99_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="shares_user_id_eb8a88_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="shares_created_a488ad_idx"
                    ),
                ],
                "unique_together": {("user", "content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("follow", "Follow"),
                            ("follow_request", "Follow Request"),
                            ("mention", "Mention"),
                            ("reel_comment", "Reel Comment"),
                            ("post_comment", "Post Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=10)),
                ("content_id", models.UUIDField(blank=True, null=True)),
                ("message", models.TextField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_06c470_idx",
                    ),
                    models.Index(
                        fields=["sender", "created_at"],
                        name="notificatio_sender__27efc9_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_4b40ec_idx",
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="notificatio_content_393656_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("post", "Post"), ("reel", "Reel")], max_length=10
                    ),
                ),
                ("content_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "likes",
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="likes_content_4ba168_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="likes_user_id_c4e8f2_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="likes_created_6ac82b_idx"
                    ),
                ],
                "unique_together": {("user", "content_type", "content_id")},
            },
        ),
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "follow_requests",
                "indexes": [
                    models.Index(
                        fields=["requester", "status"],
                        name="follow_requ_request_060f74_idx",
                    ),
                    models.Index(
                        fields=["target", "status"],
                        name="follow_requ_target__0fa6f5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="follow_requ_created_1d277b_idx"
                    ),
                ],
                "unique_together": {("requester", "target")},
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "follows",
                "indexes": [
                    models.Index(
                        fields=["follower", "created_at"],
                        name="follows_followe_23aafd_idx",
                    ),
                    models.Index(
                        fields=["following", "created_at"],
                        name="follows_followi_29b9dd_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="follows_created_95ec29_idx"
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
    ]
