# Generated by Django 4.2.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('reels_count', models.PositiveIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('show_activity_status', models.BooleanField(default=True)),
                ('allow_follow_requests', models.BooleanField(default=True)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('total_comments_received', models.PositiveIntegerField(default=0)),
                ('total_shares_received', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('last_post_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [
                    models.Index(fields=['user'], name='social_userprofil_user_id_8f1c3a_idx'),
                    models.Index(fields=['followers_count'], name='social_userprofil_followe_2b5c5f_idx'),
                    models.Index(fields=['following_count'], name='social_userprofil_followin_4d7e8c_idx'),
                    models.Index(fields=['last_activity'], name='social_userprofil_last_act_a4b7d2_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'indexes': [
                    models.Index(fields=['follower', 'created_at'], name='social_follow_followe_8f1c3a_idx'),
                    models.Index(fields=['following', 'created_at'], name='social_follow_followin_4d7e8c_idx'),
                    models.Index(fields=['created_at'], name='social_follow_create_a4b7d2_idx'),
                ],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel')], max_length=10)),
                ('content_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
                'indexes': [
                    models.Index(fields=['content_type', 'content_id'], name='social_like_content_2b5c5f_idx'),
                    models.Index(fields=['user', 'created_at'], name='social_like_user_id_8f1c3a_idx'),
                    models.Index(fields=['created_at'], name='social_like_create_a4b7d2_idx'),
                ],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel')], max_length=10)),
                ('content_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shares',
                'indexes': [
                    models.Index(fields=['content_type', 'content_id'], name='social_share_content_2b5c5f_idx'),
                    models.Index(fields=['user', 'created_at'], name='social_share_user_id_8f1c3a_idx'),
                    models.Index(fields=['created_at'], name='social_share_create_a4b7d2_idx'),
                ],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follow_requests',
                'indexes': [
                    models.Index(fields=['requester', 'status'], name='social_followrequ_request_8f1c3a_idx'),
                    models.Index(fields=['target', 'status'], name='social_followrequ_target_2b5c5f_idx'),
                    models.Index(fields=['created_at'], name='social_followrequ_create_a4b7d2_idx'),
                ],
                'unique_together': {('requester', 'target')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('activity_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('follow', 'Follow'), ('post', 'Post'), ('reel', 'Reel')], max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=10)),
                ('content_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='social_useractivit_user_id_8f1c3a_idx'),
                    models.Index(fields=['activity_type', 'created_at'], name='social_useractivit_activit_2b5c5f_idx'),
                    models.Index(fields=['target_user', 'created_at'], name='social_useractivit_target__4d7e8c_idx'),
                    models.Index(fields=['content_type', 'content_id'], name='social_useractivit_content_8f1c3a_idx'),
                    models.Index(fields=['created_at'], name='social_useractivit_create_a4b7d2_idx'),
                ],
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('follow', 'Follow'), ('follow_request', 'Follow Request'), ('mention', 'Mention'), ('reel_comment', 'Reel Comment'), ('post_comment', 'Post Comment')], max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=10)),
                ('content_id', models.UUIDField(blank=True, null=True)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [
                    models.Index(fields=['recipient', 'is_read', 'created_at'], name='social_notificati_recipien_8f1c3a_idx'),
                    models.Index(fields=['sender', 'created_at'], name='social_notificati_sender_2b5c5f_idx'),
                    models.Index(fields=['notification_type', 'created_at'], name='social_notificati_notific_4d7e8c_idx'),
                    models.Index(fields=['content_type', 'content_id'], name='social_notificati_content_8f1c3a_idx'),
                ],
                'ordering': ['-created_at'],
            },
        ),
    ]
